OUTPUT_DIR: ./output/psp_concat_batch2_down1

MODEL:
  MODEL: "psp_resnet50_voc"
  LOSS: "DiceLossV1"
  DEEP_SUP: "v2"

SOLVER:
  LR: 0.01
  EPOCHS: 100
  SAVE_INTERVAL_EPOCH: 5
  BATCH_SIZE_TRAIN: 1

DATA:
  DOWN_SAMPLE_RATE: 1.0
  DOWN_SAMPLE_RATE_TEST: 1.0
  DATASET_TRAIN: './data/data_split/0_train_backup.txt'
  DATASET_VALID: './data/data_split/0_valid_backup.txt'
  DATASET_TEST: './data/data_split/0_valid_backup.txt'

  DENSE_CROP_STRIDE: 512

  # CROP_METHOD_TRAIN: "Resize"
  # CROP_METHOD_TEST: "Resize"